### PR TITLE
Update dependencies and migrate

### PR DESCRIPTION
**Pull request by joglr**
- [x] Update all dependencies
- [x] Update remix and migrate import statements
- [x] Migrate to remix serve instead of custom server
- [x] Convert `cli.js` to typescript
- [x] Investigate which dependencies are not required in production (decreases install time for end users!)
- [x] Bundled all dependencies
- [x] Move dependencies to devDependencies
- [x] Check if package.json files property needs to be changed
- [x] Redirect to repo url if needed
- [x] Clean up PR commits

This PR is published as a prerelease:
git-truck@1.2.0-16

and can be tested with

```npx git-truck@1.2.0-16```

or ```npm i -g git-truck@1.2.0-16 && git-truck```

Please review by testing. The only difference should be the installation duration.

```
node ./scripts/benchmark.mjs 1.2.0-16 5
┌─────────┬────────────────┬──────────────────────────┬─────────────────────────────────────┐
│ (index) │    version     │ npx average time (in ms) │ global install average time (in ms) │
├─────────┼────────────────┼──────────────────────────┼─────────────────────────────────────┤
│    0    │  '1.2.0-16'    │    4352.361275047064     │         3329.4166250526905          │
│    1    │      '1.1.9'   │    7521.897275060415     │          87835.1232124865           │
└─────────┴────────────────┴──────────────────────────┴─────────────────────────────────────┘
``` 

 - **26x** faster than before when using `npm install -g git-truck && git-truck`
 - **70%** faster than before when using `npx git-truck`

This PR improves the developer experience by utilizing the built in remix dev server.

### CODE REVIEW

**Comment by mircealungu** [comment]
image

File: CONTRIBUTING.md [hunk 1]
```diff
@@ -44,3 +44,16 @@ To clean up build artefacts, cached analyzations, etc., run:
...
 npm run clean
 ```
+
+# Benchmarking
+
+A benchmark script for measuring the performance is available. Use it by running
+
+```
+node ./scripts/benchmark.mjs [tag = experimental] [reps = 1]
+
```
Comment (mircealungu) [inline CONTRIBUTING.md:54]: measuring performance of what? and how? :)

Comment (joglr) [reply CONTRIBUTING.md:54]: It is measuring the time from running `npx git-truck` and `npm i -g git-truck && git-truck` to Git Truck printing help information in the terminal.

Comment (joglr) [reply CONTRIBUTING.md:54]: I've changed the build process to bundle all the dependencies of git truck which improves installation time significantly. I have new numbers incoming in a few minutes.

Comment (joglr) [reply CONTRIBUTING.md:54]: Feel free to run the scripts now and post your results! Would be interesting to compare across systems.

File: src/routes/$repo.$.tsx [hunk 2]
```diff
@@ -2,7 +2,8 @@ import { RateReview as ReviewIcon } from "@styled-icons/material"
 import { resolve } from "path"
 import { useState } from "react"
 import { useBoolean } from "react-use"
-import { ActionFunction, ErrorBoundaryComponent, json, Link, LoaderFunction, redirect, useLoaderData } from "remix"
+import { ActionFunction, ErrorBoundaryComponent, json, LoaderFunction, redirect } from "@remix-run/node";
```
Comment (tjomson) [inline src/routes/$repo.$.tsx:5]: eslint would like to use import type

File: src/routes/$repo.$.tsx [hunk 3]
```diff
@@ -201,7 +202,7 @@ function UpdateNotifier() {
 }
 
 export default function Repo() {
-  const data = useLoaderData<RepoData>()
+  const data = useLoaderData<typeof loader>()
```
Comment (tjomson) [inline src/routes/$repo.$.tsx:205]: How is this different?

File: src/routes/$repo.$.tsx [hunk 4]
```diff
@@ -201,7 +202,7 @@ function UpdateNotifier() {
...
   const { analyzerData, gitTruckInfo } = data
```
Comment (tjomson) [inline src/routes/$repo.$.tsx:206]: can this be typed?

**Review by tjomson — APPROVED** [review]
Epic work! Install time is insanely quick
Wrote a few questions, mostly for my own understanding of the code
🚀

File: src/routes/$repo.$.tsx (hunk 3 above)
Comment (joglr) [reply src/routes/$repo.$.tsx:205]: It uses baked in remix type inference instead of an explicit type. I had some issues with the typings, but changing this solved the issues.

File: package.json [hunk 5]
```diff
@@ -112,7 +106,7 @@
     ]
   },
   "engines": {
-    "node": ">=14"
+    "node": ">=16.13.0"
```
[the remark this answers is not in the document]
Comment (joglr) [reply package.json:109]: I will check, I changed it so it matched the documentation

File: src/cli.ts [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+    let extension = ""
+
+    // If CWD or path argument is a git repo, go directly to that repo in the visualizer
+    if (await GitCaller.isGitRepo(options.path)) {
+      const repo = await GitCaller.getRepoMetadata(options.path)
+      if (repo) {
+        extension = `/${getPathFromRepoAndHead(repo.name, repo.currentHead)}`
+      }
+    }
+    printOpen(url, extension)
```
[the remark this answers is not in the document]
Comment (joglr) [reply src/cli.ts:76]: I have now fixed this, don't know if it makes a difference 🤷🏼‍♂️

File: src/routes/$repo.$.tsx (hunk 2 above)
Comment (joglr) [reply src/routes/$repo.$.tsx:5]: I have now fixed this issue across the codebase by running `npm run lint`

File: package.json (hunk 5 above)
[the remark this answers is not in the document]
Comment (joglr) [reply package.json:109]: I can't get it to work with Node 14.0.0

```
Cannot find module 'node:http'
Require stack:
- C:\Users\jonas\AppData\Roaming\npm-cache\_npx\24848\node_modules\git-truck\cli.js
```

File: scripts/publish-experimental.js [hunk 7]
```diff
@@ -0,0 +1,43 @@
+/* eslint-disable @typescript-eslint/no-var-requires */
+const { execSync } = require("child_process")
+
```
[the remark this answers is not in the document]
Comment (joglr) [reply scripts/publish-experimental.js:3]: I don't know if np can be configured to do exactly what I wanted it to, which was run a single command and publish an "anonymous" experimental version, that does not create commits or tags, with a version name based on the latest commit hash.

File: src/routes/$repo.$.tsx (hunk 4 above)
Comment (joglr) [reply src/routes/$repo.$.tsx:216]: Oh, I don't understand why this is any... I will investigate!

File: src/routes/$repo.$.tsx (hunk 3 above)
Comment (joglr) [reply src/routes/$repo.$.tsx:215]: Oh nvm, it didn't solve the issue

Comment (joglr) [reply src/routes/$repo.$.tsx:215]: I solved it by using this package: https://www.npmjs.com/package/remix-typedjson
